### ISSUE TITLE
cheeck if this will work

### ISSUE THREAD

**Issue by Ndegwadavid** [anomalous254/blog#1]
import React from 'react';
import { createRoot } from 'react-dom';
import App from './app';
import { BrowserRouter as Router, Route, Routes } from 'react-router-dom'; 
const root = createRoot(document.getElementById('root')); 
root.render(
  <Router>
    <Routes>
      <Route path='/' element={<App />} /> 
    </Routes>
  </Router>
);

**Comment by anomalous254** [comment]
Nop hio error bado iko tu ,,,, nothing is being rendered

**Comment by Ndegwadavid** [comment]
wazi nitacheki hiyo code  baadae..troubleshoot more

**Comment by Ndegwadavid** [comment]
ask also chatgpt : )

**Comment by anomalous254** [comment]
yezayaza

**Comment by Ndegwadavid** [comment]
add a readme for easier understanding the project.
